### ISSUE TITLE
Trying to run the example results in a Access Denied.

### ISSUE THREAD

**Issue by NanoAi** [sousa-andre/lcu-driver#1]
Trying to run the following code...
```
# fired when LCU API is ready to be used
@conn.ready
async def connect(connection):
    print('LCU API is ready to be used.')


# fired when League Client is closed (or disconnected from websocket)
@conn.close
async def disconnect(_):
    print('The client have been closed!')
    await connect.stop()


# subscribe to '/lol-summoner/v1/current-summoner' endpoint for the UPDATE event
# when an update to the user happen (e.g. name change, profile icon change, level, ...) the function will be called
@conn.ws.register('/lol-summoner/v1/current-summoner', event_types=('UPDATE',))
async def icon_changed(connection, event):
    print(f'The summoner {event.data["displayName"]} was updated.')


# starts the connector
conn.start()
```
Results in the following error...
```
Traceback (most recent call last):
  File "D:\Python\Python38-32\lib\site-packages\psutil\_common.py", line 446, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Python38-32\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "D:\Python\Python38-32\lib\site-packages\psutil\_common.py", line 449, in wrapper
    return fun(self)
  File "D:\Python\Python38-32\lib\site-packages\psutil\_pswindows.py", line 766, in exe
    exe = cext.proc_exe(self.pid)
PermissionError: [WinError 24] The program issued a command but the command length is incorrect: '(originated from NtQuerySystemInformation)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LeagueListener.py", line 43, in <module>
    conn.start()
  File "D:\Python\Python38-32\lib\site-packages\lcu_driver\connector.py", line 53, in start
    wrapper()
  File "D:\Python\Python38-32\lib\site-packages\lcu_driver\connector.py", line 45, in wrapper
    connection = _return_ux_process_when_available()
  File "D:\Python\Python38-32\lib\site-packages\lcu_driver\utils.py", line 25, in _return_ux_process_when_available
    process = return_process(['LeagueClientUx.exe', 'LeagueClientUx'])
  File "D:\Python\Python38-32\lib\site-packages\lcu_driver\utils.py", line 17, in return_process
    if process.name() in process_name:
  File "D:\Python\Python38-32\lib\site-packages\psutil\__init__.py", line 615, in name
    name = self._proc.name()
  File "D:\Python\Python38-32\lib\site-packages\psutil\_pswindows.py", line 750, in name
    return os.path.basename(self.exe())
  File "D:\Python\Python38-32\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=8040)
```
This happens both with running as admin, and running as a user.

I know this can be resolved by using an earlier version of "psutil", but shouldn't it also work on the latest? Is there no work around?

**Comment by NanoAi** [comment]
Downgrading PSUTIL does indeed work, very odd error though. (And I'm stupid.)
